// This file was generated by lezer-generator. You probably shouldn't edit it.
export const
  File = 1,
  Expression = 2,
  MathExpr = 3,
  MathTerm = 4,
  Number = 5,
  FunctionCall = 6,
  ToIntFunction = 7,
  String = 8,
  ToStringFunction = 9,
  ToFloatFunction = 10,
  ToTimestampFunction = 11,
  UppercaseFunction = 12,
  LowercaseFunction = 13,
  MathOperators = 14
