// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
export const parser = LRParser.deserialize({
  version: 14,
  states: "&YOVQPOOOqQPO'#CcOvQPO'#CeO{QPO'#CfO!QQPO'#CgO!VQPO'#ChO![QPO'#CiOOQO'#Cb'#CbOOQO'#C`'#C`OVQPO'#C`O!rQPO'#C_OOQO'#C^'#C^OOQO'#Ck'#CkQVQPOOO#fQPO,58}O#kQPO,59PO#pQPO,59QO#uQPO,59RO#zQPO,59SO$PQPO,59TO$UQPO,58zOOQO'#Cj'#CjOVQPO'#ClO$ZQPO,58yOOQO-E6i-E6iO$}QPO1G.iO%SQPO1G.kO%XQPO1G.lO%^QPO1G.mO%cQPO1G.nO%hQPO1G.oOOQO1G.f1G.fOOQO,59W,59WOOQO-E6j-E6jOOQO7+$T7+$TOOQO7+$V7+$VOOQO7+$W7+$WOOQO7+$X7+$XOOQO7+$Y7+$YOOQO7+$Z7+$Z",
  stateData: "%m~OcOS~OTWOdPOeXOgQOhROiSOjTOkUO~Oe^O~Oe_O~Oe`O~OeaO~OebO~OecO~OleOmeOneOoeOpeO~OTRXaRXdRXeRXgRXhRXiRXjRXkRXfRX~P!aOWiO~OTjO~OWkO~OWlO~OWmO~OWnO~OfoO~OTRaaRadRaeRagRahRaiRajRakRafRa~P!aOfrO~OfsO~OftO~OfuO~OfvO~OfwO~O",
  goto: "!caPPbfmPu{P{{{{{!R!V!]T[O]SZO]RdXUYOX]RpfXWOX]fXVOX]fTfYgQ]ORh]QgYRqg",
  nodeNames: "⚠ File Expression MathExpr MathTerm Number FunctionCall ToIntFunction String ToStringFunction ToFloatFunction ToTimestampFunction UppercaseFunction LowercaseFunction MathOperators",
  maxTerm: 32,
  skippedNodes: [0],
  repeatNodeCount: 2,
  tokenData: "*g~RfX^!gpq!grs#[xy#yyz$Oz{$T{|$Y}!O$_!P!Q$d!Q![$i!_!`$q#`#a$v#h#i%}#i#j)`#y#z!g$f$g!g#BY#BZ!g$IS$I_!g$I|$JO!g$JT$JU!g$KV$KW!g&FU&FV!g~!lYc~X^!gpq!g#y#z!g$f$g!g#BY#BZ!g$IS$I_!g$I|$JO!g$JT$JU!g$KV$KW!g&FU&FV!g~#_TOr#[rs#ns;'S#[;'S;=`#s<%lO#[~#sOW~~#vP;=`<%l#[~$OOe~~$TOf~~$YOn~~$_Ol~~$dOm~~$iOo~~$nPT~!Q![$i~$vOp~~$yP#c#d$|~%PP#k#l%S~%VP#X#Y%Y~%]P#f#g%`~%cP#V#W%f~%iP#T#U%l~%oP#g#h%r~%uP#X#Y%x~%}Ok~~&QP#c#d&T~&WS!h!i&d!k!l'R!u!v'd!v!w(X~&gP#`#a&j~&mP#c#d&p~&sP#T#U&v~&yP#h#i&|~'ROh~~'UP#b#c'X~'[P#h#i'_~'dOd~~'gP#h#i'j~'mP#f#g'p~'sP#]#^'v~'yP#b#c'|~(PP#Z#[(S~(XOg~~([P#]#^(_~(bP#a#b(e~(hP#X#Y(k~(nP#g#h(q~(tP#h#i(w~(zP#T#U(}~)QP#a#b)T~)WP#d#e)Z~)`Oi~~)cP#d#e)f~)iP#d#e)l~)oP#X#Y)r~)uP#f#g)x~){P#V#W*O~*RP#T#U*U~*XP#g#h*[~*_P#X#Y*b~*gOj~",
  tokenizers: [0],
  topRules: {"File":[0,1]},
  tokenPrec: 0
})
